name: Build HORNET
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build HORNET
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Print Go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build HORNET
        run: go build -v .

      - name: Extract commit hash
        id: sha
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: whomaniac/hornet
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile.dev
          tags: ${{ steps.sha.outputs.sha_short }}



